# SENSORS
# ----------------------------------------
[[sensor]]
name = "B0001"
descr = "current sensor"
type = "PX-AI"
com_prot = "SPI"
address = "analog_in0"
quad_gain = "0.0"
gain = "5.0"
offset = "0.0"
calibrated = "yes"

[[sensor]]
name = "EMRGY"
descr = "emergency stop button"
type = "PX-DI"
com_prot = "SPI"
address = "digital_in4"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = ""

[[sensor]]
name = "B0101"
descr = "Level sensor stabilizer tank"
type = "PX-AI"
com_prot = "SPI"
address = "analog_in1"
quad_gain = "0.0"
gain = "-9.615023474178404"
offset = "52.305164319248824"
calibrated = "yes"

[[sensor]]
name = "B0111"
descr = "Level sensor collector tube"
type = "PX-AI"
com_prot = "SPI"
address = "analog_in2"
quad_gain = "0.0"
gain = "-0.13784615384615384"
offset = "0.7653076923076922"
calibrated = "yes"

[[sensor]]
name = "B0102"
descr = "pH in stabilizer tank"
type = "EZO-pH"
com_prot = "I2C"
address = "90"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = "yes"

[[sensor]]
name = "B0103"
descr = "Temperature in stabilizer tank"
type = "EZO-RTD"
com_prot = "I2C"
address = "101"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = "yes"

[[sensor]]
name = "BM101"
descr = "over-current M0101 (stabilizer stirrer)"
type = "PX-DI"
com_prot = "SPI"
address = "digital_in6"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = ""

[[sensor]]
name = "B0201"
descr = "Level sensor evaporator"
type = "PX-AI"
com_prot = "SPI"
address = "analog_in3"
quad_gain = "-0.03976849850191494"
gain = "-2.693306026472488"
offset = "22.438821253840036"
calibrated = "yes"

[[sensor]]
name = "B0202"
descr = "pH in evaporator tank"
type = "EZO-pH"
com_prot = "I2C"
address = "99"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = "yes"

[[sensor]]
name = "B0203"
descr = "Temperature in evaporator tank"
type = "EZO-RTD"
com_prot = "I2C"
address = "102"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = "yes"

[[sensor]]
name = "BM201"
descr = "over-current M0201 (evaporator disc motor)"
type = "PX-DI"
com_prot = "SPI"
address = "digital_in7"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = ""

[[sensor]]
name = "BM202"
descr = "over-current M0201 (evaporator screw motor)"
type = "PX-DI"
com_prot = "SPI"
address = "digital_in8"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = ""

# [[sensor]]
# name = "B0301"
# descr = "Rel. humidity upstream evaporator"
# type = "EZO-HUM"
# com_prot = "I2C"
# address = "110"
# quad_gain = "0.0"
# gain = "1.0"
# offset = "0.0"
# calibrated = ""

# [[sensor]]
# name = "B0303"
# descr = "Rel. humidity downstream evaporator"
# type = "EZO-HUM"
# com_prot = "I2C"
# address = "111"
# quad_gain = "0.0"
# gain = "1.0"
# offset = "0.0"
# calibrated = ""

[[sensor]]
name = "B0401"
descr = "Level switch stabilizer tank"
type = "PX-DI"
com_prot = "SPI"
address = "digital_in0"
quad_gain = "0.0"
gain = "1.0"
offset = "0.0"
calibrated = ""


# ACTUATORS
# ----------------------------------------
[[actuator]]
name = "M0101"
descr = "stabilizer stirrer"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out8"

[[actuator]]
name = "M0102"
descr = "evaporaor feed pump (peri pump)"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out2"

[[actuator]]
name = "M0111"
descr = "collector drain pump (peri pump)"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out3"

[[actuator]]
name = "M0112"
descr = "collector flush pump (peri pump)"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out4"

[[actuator]]
name = "M0201"
descr = "disc motor"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out7"

[[actuator]]
name = "M0202"
descr = "screw motor"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out6"

[[actuator]]
name = "M0203"
descr = "concentrate discharge pump (peri pump)"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out5"

[[actuator]]
name = "M0204"
descr = "evaporator fan(s) blowing out"
type = "PX-Rel"
com_prot = "SPI"
address = "relay0"

[[actuator]]
name = "M0205"
descr = "evaporator fan(s) blowing in"
type = "PX-Rel"
com_prot = "SPI"
address = "relay1"

[[actuator]]
name = "M0301"
descr = "dehumidifier 230V"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out0"

[[actuator]]
name = "M0501"
descr = "stripping air pump"
type = "PX-DO"
com_prot = "SPI"
address = "digital_out9"
