machine_id                 = "NH-25-002"
dataq_sampling_interval    = "10"
initial_wait_time          = "5"
abort_flag                 = "False"

# collector tube
tau_M0111_runtime          = "60"
tau_M0111_delay            = "30"
tau_M0112_runtime          = "15"
tau_M0112_delay            = "30"
threshold_min_B0111        = "0.1"   # minimum input volume in collector for event detection

# stabilizer stirrer
tau_M0101_interval         = "1800"
tau_M0101_runtime          = "60"
tau_M0101_delay            = "300"

# evaporator feed
tau_M0102_interval         = "7200"
tau_M0102_runtime          = "109"
tau_M0102_delay            = "0"
threshold_min_B0101        = "15.0"    # minimum liquid level in stabilizer
threshold_max_B0101        = "40.3"    # maximum liquid level in stabilizer (overflow position)
threshold_min_B0102        = "11.0"   # minimum pH value in stabilizer

# evaporation
tau_M0201_interval         = "7200"
tau_M0201_runtime          = "3600"
threshold_min_B0201        = "13"      # minimum liquid level in evaporator
threshold_min_B0202        = "11.0"   # minimum pH value in evaporator

# concentrate discharge
tau_M0203_interval         = "86400"
tau_M0203_runtime          = "0"
tau_M0203_delay            = "0"

# sensor print to prompt
print_B0001                = "False"
print_EMRGY                = "False"
print_B0101                = "False"
print_B0102                = "False"
print_B0103                = "False"
print_BM101                = "False"
print_B0111                = "False"
print_B0201                = "False"
print_B0202                = "False"
print_B0203                = "False"
print_BM201                = "False"
print_BM202                = "False"
print_B0301                = "False"
print_B0303                = "False"
print_B0401                = "False"

# relaunch after over-current
relaunch_M0101             = "False"
relaunch_M0201             = "False"
relaunch_M0202             = "False"

# Maintenance
CaOH2_dosing               = "10"    # assumed consumption (disolution + slip) im g/L
CaOH2_refill               = "False" # opens dialog for Ca(OH)2 refil procedure during operation